### ISSUE TITLE
Download links are down

### ISSUE THREAD

**Issue by ouenal** [daveredrum/ScanRefer#22]
Hi,

All links are all down alongside the online dataset browser. While working on a fix, can you provide a temporary download link for the camera poses you recently released (maybe via Google Drive)?

**Comment by daveredrum** [comment]
Hi @ouenal, it should be fixed now - Can you give it a shot?

**Comment by ouenal** [comment]
I'm still getting the following error on the dataset browser:

kaldir.vc.in.tum.de didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by daveredrum** [comment]
Can you try [this link](https://kaldir.vc.in.tum.de:8080/apps/main)? It works fine for me.

**Comment by ouenal** [comment]
That link works. Interestingly the link under https://daveredrum.github.io/ScanRefer/ still doesn't.

**Comment by daveredrum** [comment]
It seems like an "https" issue to me again. I've fixed it and it works on my side - Could you check?

**Comment by ouenal** [comment]
Yes it works, cheers.
